# -*- coding: utf-8 -*-
"""sensitivity_analysis.ipynb

Automatically generated by Colab.
"""

import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
import math
from utils import *

class StructEnvironment():
    def __init__(self):

        # Constants
        self.E = 200 * 10**6  # (N/m^2) Young's modulus
        self.nodes = np.genfromtxt('initial_structure/nodes.csv',delimiter=',',dtype=np.float16)
        self.step_size = 0.01
        self.A = 0.01  # default size of element

        # Supports
        self.restrained_DOF = np.genfromtxt('initial_structure/support.csv',delimiter=',',dtype=np.int8)

        # Members
        self.members = np.genfromtxt('initial_structure/members.csv',delimiter=',',dtype=np.int8)
        self.DOF = calc_DOF(self.members)
        self.element_count = len(self.members)

        # Loading
        self.point_loads = np.array([np.zeros(self.DOF)]).T.ravel()
        self.point_loads[36] = -100*1e3
        self.point_loads[37] = -100*1e3

        # Define any additional environment-specific variables here
        self.current_step = 0
        self.rotations, self.lengths = calc_rotation_length(self.members, self.nodes)

        # Constraint
        self.total_area = sum(self.A*self.lengths)

    def analyse(self,members_area):
        K = build_K(self.members, members_area, self.rotations, self.lengths, self.E)
        del_K__del_area = build_del_K__del_area(self.members, members_area, self.rotations, self.lengths, self.E)
        U_free = calc_displacement(K, self.point_loads, self.restrained_DOF)
        UG = assemble_UG(U_free, self.DOF, self.restrained_DOF)
        U_2d = UG.reshape((-1,2))
        self.deflections = []
        def_members = np.zeros((self.element_count))
        F_members = np.zeros((self.element_count))
        for i in range(self.element_count):
            L = self.lengths[i]
            F_member,def_member =  calc_member_forces_def(self.members[i],members_area[i],self.rotations[i],L,U_2d,self.E)
            def_members[i] = def_member/L
            F_members[i] = F_member
        return F_members,def_members,UG,del_K__del_area,K

    def calculate_cost(self,UG): # global compliance
        return UG@self.point_loads

    def reset(self):
        self.current_step +=1
        members_area = np.random.normal(loc=self.A,scale=self.A/3,size=len(self.members))
        members_area[members_area<1e-4] = 1e-4
        members_area = self.redistribute_material(members_area)
        return members_area

    def redistribute_material(self,members_area):
        members_area = members_area * (self.total_area/sum(members_area*self.lengths))
        return members_area

    def update_area(self,members_area):
        random_element = np.random.randint(self.element_count)
        members_area[random_element] = members_area[random_element] + np.random.normal(loc=0,scale=self.A/5)
        members_area[members_area<1e-4] = 1e-4
        members_area = self.redistribute_material(members_area)
        return members_area

    def step(self, members_area):
        F_members,def_members,UG,del_K__del_area = self.analyse(members_area)
        cost = self.calculate_cost(def_members)
        return cost,F_members,UG

    def render(self,members_area,F_members,UG):
        plot_deflection(self.members, self.nodes,F_members, members_area,UG ,2,self.current_step)

"""# Adjoint Method ( Sensivity Analysis )"""

def calculate_del_Kg__del_area(theta,mag,E,A):

    c = math.cos(theta)
    s = math.sin(theta)

    K11 = (E/mag)*np.array([[c**2,c*s],[c*s,s**2]]) #Top left quadrant of del_Kg__del_area
    K12 = (E/mag)*np.array([[-c**2,-c*s],[-c*s,-s**2]]) #Top right quadrant of del_Kg__del_area
    K21 = (E/mag)*np.array([[-c**2,-c*s],[-c*s,-s**2]]) #Bottom left quadrant of del_Kg__del_area
    K22 = (E/mag)*np.array([[c**2,c*s],[c*s,s**2]]) #Bottom right quadrant of del_Kg__del_area

    return [K11, K12, K21,K22]

def build_del_K__del_area(members, members_area, orientations, lengths, E):
    n_DOF = calc_DOF(members)
    Kp = np.zeros([n_DOF, n_DOF])  # Initialise the primary stiffness matrix
    d_Kp__d_area = np.zeros((n_DOF, n_DOF,len(members)))
    for dimension in range(len(members)):
        for n, mbr in enumerate(members):
            # note that enumerate adds a counter to an iterable (n)

            # Calculate the quadrants of the global stiffness matrix for the member
            theta = orientations[n]
            L = lengths[n]
            A = members_area[n]
            if n == dimension:
                [K11, K12, K21, K22] = calculate_del_Kg__del_area(theta, L, E, A)
            else:
                continue

            node_i = mbr[0]  # Node number for node i of this member
            node_j = mbr[1]  # Node number for node j of this member

            # Primary stiffness matrix indices associated with each node

            i = 2* node_i
            j = 2 * node_j

            d_Kp__d_area[i : i + 2, i : i + 2,dimension] = Kp[i : i + 2, i : i + 2] + K11
            d_Kp__d_area[j : j + 2, j : j + 2,dimension] = Kp[j : j + 2, j : j + 2] + K22
            d_Kp__d_area[i : i + 2, j : j + 2,dimension] = Kp[i : i + 2, j : j + 2] + K12
            d_Kp__d_area[j : j + 2, i : i + 2,dimension] = Kp[j : j + 2, i : i + 2] + K21

    return d_Kp__d_area

def gradient(K,F,U,del_K__del_area,A,lengths,C,restrained_DOF):
    K_reduced = build_matrix_reduced(K,restrained_DOF)
    del_K_reduced__del_area = build_matrix_reduced(del_K__del_area,restrained_DOF)
    F_reduced = build_matrix_reduced(F,restrained_DOF)
    U_reduced = build_matrix_reduced(U,restrained_DOF)

    lambda_ = np.linalg.solve(K_reduced.T,F_reduced.T) # solving adjoint equation
    d_L__d_area = np.zeros((len(F),len(lengths))) # ( N, P)
    temp = np.zeros((len(U_reduced),len(lengths)))
    for i in range(len(lengths)):
        temp[:,i] = del_K_reduced__del_area[:,:,i]@U_reduced # d_k/d_theta * U

    d_L__d_area =  - lambda_.T @ temp # - lambda * d_k/d_theta * U
    return d_L__d_area

env = StructEnvironment()
cost = []

members_area = env.reset()
members_area = np.ones_like(members_area) * env.A

removed_indices = []
i = 0
while True:
    F_members,def_members,UG,del_K__del_area,K = env.analyse(members_area) # del_K__del_area.shape = N*N*P
    new_cost = env.calculate_cost(UG)
    if (len(cost)>0) and (new_cost > 5*cost[i-1]):
        break
    cost.append(new_cost)

    env.render(members_area,F_members,UG)
    gradient_area = gradient(K,env.point_loads,UG,del_K__del_area,members_area,env.lengths,env.total_area,env.restrained_DOF)
    edges_sorted_by_importance = np.argsort(gradient_area)[::-1]
    j = 0
    while True:
        if edges_sorted_by_importance[j] not in removed_indices:
            removed_indices.append(edges_sorted_by_importance[j])
            break
        j +=1

    print(f"iteration: {i} , cost: {cost[i]}") # cost is the same as compliance : F.T @ U
    members_area[np.array(removed_indices)] = 1e-4 # set size of the removed elements very close to 0
    members_area = env.redistribute_material(members_area) # redistribute the material among the elements which are not removed
    env.current_step +=1
    i += 1

cost = np.array(cost)

fig = plt.figure(figsize=(3,3),dpi=80)
axes = fig.add_axes([0.1,0.1,2,2])
axes.plot(cost)
axes.set_xlabel('iteration')
axes.set_ylabel('cost')
axes.set_title('Cost : global compliance')
