# -*- coding: utf-8 -*-
"""sensitivity_analysis.ipynb

Automatically generated by Colab.
"""

import os
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
import math
from utils import *

OUTPUT_DIR = 'results'

class StructEnvironment():
    def __init__(self):

        # Constants
        self.E = 200 * 10**6  # (N/m^2) Young's modulus
        self.nodes = np.genfromtxt('initial_structure/nodes.csv',delimiter=',',dtype=np.float16)
        self.step_size = 0.01
        self.A = 0.01  # default size of element

        # Supports
        self.restrained_DOF = np.genfromtxt('initial_structure/support.csv',delimiter=',',dtype=np.int8)

        # Members
        self.members = np.genfromtxt('initial_structure/members.csv',delimiter=',',dtype=np.int8)
        self.DOF = calc_DOF(self.members)
        self.element_count = len(self.members)

        # Loading
        self.point_loads = np.array([np.zeros(self.DOF)]).T.ravel()
        self.point_loads[36] = -100*1e3
        self.point_loads[37] = -100*1e3

        # Define any additional environment-specific variables here
        self.current_step = 0
        self.rotations, self.lengths = calc_rotation_length(self.members, self.nodes)

        # Constraint
        self.total_area = sum(self.A*self.lengths)

    def analyse(self,members_area):
        K = build_K(self.members, members_area, self.rotations, self.lengths, self.E)
        U_free = calc_displacement(K, self.point_loads, self.restrained_DOF)
        UG = assemble_UG(U_free, self.DOF, self.restrained_DOF)
        U_2d = UG.reshape((-1,2))
        self.deflections = []
        def_members = np.zeros((self.element_count))
        F_members = np.zeros((self.element_count))
        for i in range(self.element_count):
            L = self.lengths[i]
            F_member,def_member =  calc_member_forces_def(self.members[i],members_area[i],self.rotations[i],L,U_2d,self.E)
            def_members[i] = def_member/L
            F_members[i] = F_member
        return F_members,def_members,UG,K

    def calculate_cost(self,UG): # global compliance
        return UG@self.point_loads

    def reset(self):
        self.current_step +=1
        members_area = np.random.normal(loc=self.A,scale=self.A/3,size=len(self.members))
        members_area[members_area<1e-4] = 1e-4
        members_area = self.redistribute_material(members_area)
        return members_area

    def redistribute_material(self,members_area):
        members_area = members_area * (self.total_area/sum(members_area*self.lengths))
        return members_area

    def update_area(self,members_area):
        random_element = np.random.randint(self.element_count)
        members_area[random_element] = members_area[random_element] + np.random.normal(loc=0,scale=self.A/5)
        members_area[members_area<1e-4] = 1e-4
        members_area = self.redistribute_material(members_area)
        return members_area

    def step(self, members_area):
        F_members,def_members,UG,K = self.analyse(members_area)
        cost = self.calculate_cost(def_members)
        return cost,F_members,UG

    def render(self,members_area,F_members,UG,output_dir=OUTPUT_DIR):
        plot_deflection(self.members, self.nodes,F_members, members_area,UG ,2,self.current_step,output_dir=output_dir)

"""# Adjoint Method ( Sensivity Analysis )

Compliance J = F^T U is a SELF-ADJOINT problem: K is symmetric, dJ/dU = F,
so the adjoint equation K^T λ = F yields λ = U. The full adjoint sensitivity
formula −λ^T (dK/dA_e) U then collapses to a per-element closed form
involving only the local axial strain — no global dK/dA tensor and no second
linear solve are needed.

For ANY OTHER objective (peak stress, displacement at a node, eigenvalue,
buckling load, etc.) this shortcut does NOT apply: you must solve the
adjoint system K^T λ = ∂J/∂U and form −λ^T (dK/dA_e) U explicitly.
"""

def gradient(def_members, lengths, E):
    # Self-adjoint compliance shortcut.
    # dK_e/dA_e = (E/L_e) b_e b_e^T with b_e^T u_e = axial elongation = strain·L_e,
    # so dJ/dA_e = −(E/L_e)(b_e^T u_e)^2 = −E · L_e · strain_e^2.
    return -E * lengths * def_members**2


# ---------------------------------------------------------------------------
# General adjoint machinery — use these for non-self-adjoint objectives
# (peak stress, nodal displacement, eigenvalues, buckling, etc.).
# For compliance with fixed loads, prefer the `gradient()` shortcut above.
# ---------------------------------------------------------------------------

def calculate_del_Kg__del_area(theta, mag, E, A):
    c = math.cos(theta)
    s = math.sin(theta)

    K11 = (E/mag)*np.array([[c**2,c*s],[c*s,s**2]])
    K12 = (E/mag)*np.array([[-c**2,-c*s],[-c*s,-s**2]])
    K21 = (E/mag)*np.array([[-c**2,-c*s],[-c*s,-s**2]])
    K22 = (E/mag)*np.array([[c**2,c*s],[c*s,s**2]])

    return [K11, K12, K21, K22]


def build_del_K__del_area(members, members_area, orientations, lengths, E):
    n_DOF = calc_DOF(members)
    Kp = np.zeros([n_DOF, n_DOF])
    d_Kp__d_area = np.zeros((n_DOF, n_DOF, len(members)))
    for dimension in range(len(members)):
        for n, mbr in enumerate(members):
            theta = orientations[n]
            L = lengths[n]
            A = members_area[n]
            if n == dimension:
                [K11, K12, K21, K22] = calculate_del_Kg__del_area(theta, L, E, A)
            else:
                continue

            node_i = mbr[0]
            node_j = mbr[1]
            i = 2 * node_i
            j = 2 * node_j

            d_Kp__d_area[i:i+2, i:i+2, dimension] = Kp[i:i+2, i:i+2] + K11
            d_Kp__d_area[j:j+2, j:j+2, dimension] = Kp[j:j+2, j:j+2] + K22
            d_Kp__d_area[i:i+2, j:j+2, dimension] = Kp[i:i+2, j:j+2] + K12
            d_Kp__d_area[j:j+2, i:i+2, dimension] = Kp[j:j+2, i:i+2] + K21

    return d_Kp__d_area


def gradient_general(K, dJ_dU, U, del_K__del_area, lengths, restrained_DOF):
    # Full adjoint sensitivity for an arbitrary objective J(U, A).
    # Caller supplies ∂J/∂U (vector over all DOF). Solves K^T λ = ∂J/∂U,
    # then dJ/dA_e = ∂J/∂A_e − λ^T (∂K/∂A_e) U  (the explicit ∂J/∂A_e term
    # must be added by the caller if it is nonzero). in other words, 
    # it returns only the −λ^T (∂K/∂A_e) U term. 
    # If your future J has explicit dependence on A (e.g., a volume penalty, or a stress
    # formula that divides by A), you'll need to add ∂J/∂A_e at the call site.
    K_reduced = build_matrix_reduced(K, restrained_DOF)
    dKdA_reduced = build_matrix_reduced(del_K__del_area, restrained_DOF)
    dJdU_reduced = build_matrix_reduced(dJ_dU, restrained_DOF)
    U_reduced = build_matrix_reduced(U, restrained_DOF)

    lambda_ = np.linalg.solve(K_reduced.T, dJdU_reduced)

    temp = np.zeros((len(U_reduced), len(lengths)))
    for i in range(len(lengths)):
        temp[:, i] = dKdA_reduced[:, :, i] @ U_reduced

    return -lambda_.T @ temp


def oc_update(A, dJ_dA, lengths, V_target,
              A_min=1e-4, A_max=None, move=0.2, eta=0.5,
              mu_lo=1e-12, mu_hi=1e12, tol=1e-6):
    # Optimality-Criteria update for compliance minimization under a fixed
    # volume constraint Σ A_e L_e = V_target.
    #
    # Update rule:  A_new = clip( A · (−dJ/dA / (μ L))^η,
    #                             max(A_min, A(1−move)),
    #                             min(A_max, A(1+move)) )
    # μ is found by bisection so the volume constraint is met. For compliance
    # dJ/dA ≤ 0 so −dJ/dA ≥ 0 and the root inside the parentheses is real.
    if A_max is None:
        A_max = 100.0 * A.max()
    neg_dJ = np.maximum(-dJ_dA, 0.0)
    lo, hi = mu_lo, mu_hi
    while (hi - lo) / (hi + lo) > tol:
        mu = 0.5 * (lo + hi)
        B_eta = (neg_dJ / (mu * lengths + 1e-30)) ** eta
        A_trial = A * B_eta
        A_new = np.minimum(A_trial, np.minimum(A_max, A * (1.0 + move)))
        A_new = np.maximum(A_new,   np.maximum(A_min, A * (1.0 - move)))
        if np.sum(A_new * lengths) - V_target > 0:
            lo = mu  # too much volume → tighten penalty
        else:
            hi = mu
    return A_new


os.makedirs(OUTPUT_DIR, exist_ok=True)

env = StructEnvironment()
cost = []
members_area = np.ones(env.element_count) * env.A
V_target = env.total_area

max_iter = 150
change_tol = 1e-3 * env.A

for i in range(max_iter):
    F_members, def_members, UG, K = env.analyse(members_area)
    new_cost = env.calculate_cost(UG)
    cost.append(new_cost)

    env.render(members_area, F_members, UG)
    dJ_dA = gradient(def_members, env.lengths, env.E)
    A_new = oc_update(members_area, dJ_dA, env.lengths, V_target)

    change = np.abs(A_new - members_area).max()
    print(f"iteration: {i} , cost: {new_cost:.4f} , max ΔA: {change:.3e}")
    members_area = A_new
    env.current_step += 1

    if change < change_tol:
        print(f"converged at iteration {i}")
        break

cost = np.array(cost)

fig = plt.figure(figsize=(6,4), dpi=100)
axes = fig.add_subplot(1, 1, 1)
axes.plot(cost, marker='o', markersize=3)
axes.set_xlabel('iteration')
axes.set_ylabel('compliance (F·U)')
axes.set_title('OC convergence — global compliance vs iteration')
axes.grid(True, alpha=0.3)
fig.tight_layout()
fig.savefig(f'{OUTPUT_DIR}/cost_vs_iteration.png', bbox_inches='tight')
plt.close(fig)
print(f"saved cost curve + {len(cost)} structure frames to '{OUTPUT_DIR}/'")
